import { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-neutral-900 text-white">
        <Header />
        <div className="h-full min-h-screen">
          <main className="mx-0 md:mx-16">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
